@LibraryApi_HostAddress = http://localhost:5038

GET {{LibraryApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{LibraryApi_HostAddress}}/register
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "Test123!"
}

###

POST {{LibraryApi_HostAddress}}/login?useCookies=true
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "Test123!"
}